---
- name: Install ClickHouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install and Configure Nginx
  hosts: lighthouse
  become: true
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Nginx | Install epel-release
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Nginx | Install package
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Restart Nginx

    - name: Nginx | Create configuration
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Restart Nginx

- name: Install Lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role
