#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMKD9OjOpIXyieUs2a0NRdYuu3zq6hC/UtvH4HorSc8f user@WIN-5A0R0P8JCOL

runcmd:
  - echo 'user ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/user
  - chmod 0440 /etc/sudoers.d/user
  - apt update
  - apt install -y apache2 php mysql-server
  - echo '<html><body><h1>Hello from LAMP VM!</h1><img src="https://storage.yandexcloud.net/student-bucket/my-image.jpg"/></body></html>' > /var/www/html/index.html
  - systemctl start apache2