apiVersion: v1
kind: ConfigMap
metadata:
  name: conf-nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>CUSTOM PAGE</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h1>This is a CUSTOM Nginx page</h1>
        <p>Server: {{HOSTNAME}} (Pod: <span id="pod-name">unknown</span>)</p>
        <p>Request time: <span id="time"></span></p>

        <script>
            document.getElementById('time').textContent = new Date().toISOString();
        </script>
    </body>
    </html> 