apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nginx-deployment
  labels:
    app: multitool-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool-nginx
  template:
    metadata:
      labels:
        app: multitool-nginx
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
