apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    app: multitool-nginx
  ports:
    - name: web
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: mt
      protocol: TCP
      port: 9002
      targetPort: 8080
